version: '3.7'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - /home/fred/repos/datadb:/data/db
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge
